import { observe } from "@catanarchy/engine";
import { useCallback, useState } from "react";
import { Board } from "./Board.js";
import { Controls } from "./Controls.js";
import { Feed, type FeedItem } from "./Feed.js";
import { negotiationFeedItems } from "./NegotiationTimeline.js";
import { phaseText } from "./phase.js";
import { Players } from "./Players.js";
import type { LoadedRunReport } from "./RunReport.js";
import { decisionFeedItems, sessionSummaries, sessionText } from "./traces.js";
import { useTimestampPlayback } from "./useTimestampPlayback.js";

export interface SavedRunViewerProps {
  readonly run: LoadedRunReport;
  readonly live?: boolean;
}

const SPEEDS = [1, 2, 5, 10, 20] as const;

const timingNote = (source: LoadedRunReport["timingSource"]): string => {
  switch (source) {
    case "recorded-time":
      return "recorded time";
    case "recorded-model-time":
      return "recorded model time";
    case "mixed":
      return "recorded model time, 1 s gaps";
    case "synthetic":
      return "1 s per command";
  }
};

const originNote = (run: LoadedRunReport): string => {
  const origin = run.initialStateOrigin;
  if (origin === null) return "board origin unavailable";
  return origin.type === "generated"
    ? `board generated by ${origin.generatorId} from seed ${origin.seed}`
    : `board observed by ${origin.adapterId}`;
};

const generatorNote = (match: LoadedRunReport["generatorMatch"]): string => {
  switch (match) {
    case "matches-current":
      return "matches current generator";
    case "differs-from-current":
      return "differs from current generator";
    case "not-applicable":
      return "generator check not applicable";
    case "pending":
      return "generator check pending";
  }
};

const commandNote = (verification: LoadedRunReport["commandVerification"]): string => {
  switch (verification) {
    case "exact":
      return "native commands verified exactly";
    case "not-applicable":
      return "native command check not applicable";
    case "pending":
      return "native command check pending";
  }
};

/** Optional `?frame=N` selects the initial one-based frame; the URL never carries match data. */
const initialFrame = (count: number, live: boolean): number => {
  const requested = Number(new URLSearchParams(window.location.search).get("frame"));
  return Number.isInteger(requested) && requested >= 1
    ? Math.min(requested, count) - 1
    : live
      ? count - 1
      : 0;
};

const totalPlaybackTime = (run: LoadedRunReport): number => run.frames.at(-1)?.offsetMs ?? 0;

const gameFeedItems = (events: ReadonlyArray<LoadedRunReport["events"][number]>): FeedItem[] =>
  events.map((event) => ({
    key: `event:${event.sequence}`,
    sequence: event.sequence,
    order: Number.MIN_SAFE_INTEGER,
    kind: "event",
    text: event.event.type,
  }));

export const SavedRunViewer = ({ run, live = false }: SavedRunViewerProps) => {
  const [speedIndex, setSpeedIndex] = useState(0);
  const speed = SPEEDS[speedIndex] ?? 1;
  const { frameIndex, offsetMs, playing, seek, seekOffset, togglePlaying } = useTimestampPlayback(
    run.frames,
    initialFrame(run.frames.length, live),
    live,
    speed,
  );
  const totalMs = totalPlaybackTime(run);
  const frame = run.frames[frameIndex] ?? run.frames.at(-1);
  if (frame === undefined) throw new Error("The run has no replay frame.");
  const state = frame.state;
  const observation = observe(state, { type: "public" });
  const visibleEvents = run.events.slice(0, frame.gameEventCount);
  const visibleNegotiationEvents = run.negotiation.events.slice(0, frame.negotiationEventCount);
  const visibleDecisions = run.decisions.slice(0, frame.decisionCount);
  const visibleNegotiationDecisions = run.negotiationDecisions.slice(
    0,
    frame.negotiationDecisionCount,
  );
  const sessions = sessionSummaries([...visibleDecisions, ...visibleNegotiationDecisions]);
  const visibleNegotiation = { ...run.negotiation, events: visibleNegotiationEvents };
  const items = [
    ...gameFeedItems(visibleEvents),
    ...negotiationFeedItems(visibleNegotiation, visibleEvents),
    ...decisionFeedItems(visibleDecisions, "decision"),
    ...decisionFeedItems(visibleNegotiationDecisions, "negotiation-decision"),
  ];

  const cycleSpeed = useCallback(() => setSpeedIndex((index) => (index + 1) % SPEEDS.length), []);
  const sessionSeats = new Set(run.sessionSeatIds);

  return (
    <main className="viewer">
      <div className="board-pane">
        <Board
          observation={observation}
          legalActions={[]}
          onAction={() => {}}
          interactive={false}
        />
      </div>
      <Controls
        index={frameIndex}
        count={run.frames.length}
        onSeek={seek}
        playback={{
          playing,
          onToggle: togglePlaying,
          speed,
          onSpeed: cycleSpeed,
          note: timingNote(run.timingSource),
          elapsedMs: offsetMs,
          totalMs,
          onSeekTime: seekOffset,
        }}
      />
      <aside>
        <header className="status" aria-live="polite">
          <strong>{phaseText(state)}</strong>
          <small>
            {live && run.status === "partial" ? <b className="live">live</b> : null}
            <span>{state.matchId}</span> · event {state.sequence} ·{" "}
            <a href="?mode=play">play locally</a>
          </small>
          <small>
            replay valid · {originNote(run)} · {generatorNote(run.generatorMatch)} ·{" "}
            {commandNote(run.commandVerification)}
          </small>
        </header>
        <Players
          observation={observation}
          note={(id) => (
            <>
              {sessionText(sessions.get(id))}
              {sessionSeats.has(id) ? (
                <>
                  {" · "}
                  <a href={`/__catanarchy/session/${encodeURIComponent(id)}`}>Pi session</a>
                </>
              ) : null}
            </>
          )}
        />
        <Feed items={items} empty="No records yet." label="Run feed" />
      </aside>
    </main>
  );
};
